server:
  port: 8081
  servlet:
    context-path: /erp
logging:
  level:
    org.springframework: info
spring:
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active:
      - local
      - dev
  application:
    name: erp-application
  main:
    allow-circular-references: true
app:
  application-name: erp-application
  tokens:
    jwt-secret: ${JWT_SECRET}
    refresh-token:
      expired: 120
    access-token:
      expired: 60
