server:
  port: 8081
  servlet:
    context-path: /erp
#logging:
#  level:
#    org.springframework: TRACE
spring:
  logging:
    level:
      org.springframework: TRACE
  datasource:
    driver-class-name: org.postgresql.Driver
    username: erp_app
    password: password
    url: jdbc:postgresql://192.168.1.114:5432/erp_db
    name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active:
      - local
  application:
    name: erp-application
  main:
    allow-circular-references: true
app:
  application-name: saintcare
  tokens:
    jwt-secret: SECRETSECRETSECRETSECRETSECRETSECRETSECRETSECRETSECRET
    refresh-token:
      expired: 120
    access-token:
      expired: 60
